name: is-tech-labs-tests
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@1.2.1
        with:
          java-version: 17
          maven-version: 3.6.3

      - name: Run "banks-java" tests with Maven
        run: mvn -B test --file banks-java/pom.xml

      - name: Run "kotiki-java" tests with Maven
        run: mvn -B test --file kotiki-java/pom.xml